FROM mambaorg/micromamba:latest

USER root

WORKDIR /app

# Install system dependencies including git
RUN apt-get update && apt-get install -y \
    libexpat1 \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy environment file and entrypoint
COPY environment-dev.yml /app/environment-dev.yml
COPY entrypoint.py /app/

# Create conda environment
RUN micromamba env create -n carveme -f environment-dev.yml


ENTRYPOINT ["micromamba", "run", "-n", "carveme", "python", "entrypoint.py"]