name: carveme
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - diamond
  - pyscipopt
  - pip
  - git
  - pip:
    - numpy
    - scipy
    - sympy
    - python-libsbml
    - git+https://github.com/Robaina/carveme_expanded_universe.git