name: carveme
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - diamond
  - pyscipopt
  - pip
  - pip:
      - numpy
      - scipy
      - sympy
      - python-libsbml
      - carveme
